### ISSUE TITLE
Position Datei einfügen - erste Ebene

### ISSUE THREAD

**Issue by planepix** [Zeromax/contao-sb-admin#1]
Wenn die Dateiverwaltung geöffnet wird, ist das Einfüge-Icon auf der obersten Ebene nicht rechtsbündig wie die anderen Icons, sondern direkt nach dem text auf der linken Seite.

Screenshot aus Chrome.
![dateiverwaltung-sbadmin](https://cloud.githubusercontent.com/assets/1823889/9207351/606c8898-406d-11e5-9499-ef93d5ad938a.png)

**Comment by Zeromax** [comment]
fixed in 4e53f075117075517ddfbf85c438e8c78f9763b8
