### ISSUE TITLE
Darstellung auf Desktop-Viewport als mobile Darstellung (zu schmal)

### ISSUE THREAD

**Issue by planepix** [Zeromax/contao-sb-admin#12]
Hi Andi,

auf dem Deesktop (Viewport größer als 1400px) wird bei der Seitenstruktur-Ansicht nicht auf volle Breite gerendert, sondern nur in einer schmalen Ansicht (siehe Screenshot).
Und auch in vielen anderen Ansichten (Artikel, Nachrichten) ist die Darstellung zu schmal (die Icons sitzen nicht rechts gefloatet).

![screenshot-2015-09-08 09-10-12](https://cloud.githubusercontent.com/assets/1823889/9728615/9396eea0-5609-11e5-9064-e47a563a537e.png)

**Comment by Zeromax** [comment]
@planepix Kannst du bitte einen Screenshot machen?

**Comment by Zeromax** [comment]
Ok Danke. @planepix ich kann das nicht reproduzieren. Hast du schon den Skriptcache geleert?
Und auch den internen Cache?

Ich schau dass ich bald mal eine Version im Repo veröffentliche und via composer zur Verfügung stelle, dann macht das alles Contao...

Laut deinem Screenshot ist das aber nicht die aktuellste Version aus dem Repo. Ich habe die Breadcrumb geändert und Überschrift angepasst.
Die Listing passt auch soweit nicht

**Comment by Zeromax** [comment]
Update Problem
