### ISSUE TITLE
short open tag problem

### ISSUE THREAD

**Issue by Zeromax** [Zeromax/contao-sb-admin#15]
see https://community.contao.org/de/showthread.php?59192-sb-admin-Alternatives-Backend-Theme&p=384671&viewfull=1#post384671

**Comment by Zeromax** [comment]
@BugBuster1701 kannst du das bitte überprüfen?

Ich hoffe ich habe alles gefunden.

**Comment by BugBuster1701** [comment]
Sieht gut aus. Konnte bisher nichts in der Richtung finden.

**Comment by Zeromax** [comment]
Sauber. Danke für die Rückmeldung.

Ich lass es trotzdem mal noch offen, falls was auftaucht

**Comment by Zeromax** [comment]
Konnte keine weiteren Probleme mehr feststellen.
