### ISSUE TITLE
Notification in Navbar

### ISSUE THREAD

**Issue by Zeromax** [Zeromax/contao-sb-admin#23]
That there is a Notification should be more Prominent.

see https://community.contao.org/de/showthread.php?59192-sb-admin-Alternatives-Backend-Theme/page2&p=386206&viewfull=1#post386206

**Comment by Zeromax** [comment]
![capture20151003002648508](https://cloud.githubusercontent.com/assets/1867177/10259181/a800dee0-6965-11e5-887e-0a7179f1976a.png)

Add a red shadow on page load.

**Comment by cliffparnitzky** [comment]
:+1
