### ISSUE TITLE
Problems with paste hint

### ISSUE THREAD

**Issue by cliffparnitzky** [Zeromax/contao-sb-admin#28]
When creating new pages, the paste hint hides the button for the position:

![screen-01-neue root page](https://cloud.githubusercontent.com/assets/1247552/11424281/ff896d6a-944b-11e5-81fa-e5bce7ae1b78.jpg)

![screen-02-new_page](https://cloud.githubusercontent.com/assets/1247552/11424285/0535e108-944c-11e5-85f2-8b72821c77c7.jpg)

The same probleme occures when creating a new content element in an empty article (via header button):

![screen-04-new_ce](https://cloud.githubusercontent.com/assets/1247552/11424324/57d9e24c-944c-11e5-8c3f-568c9cabda03.jpg)

**Comment by Zeromax** [comment]
I hate the paste hint... ;)

**Comment by cliffparnitzky** [comment]
:grin: me too

**Comment by Zeromax** [comment]
Hm. This could be a feature: Do not show hints. Maybe later...

**Comment by Zeromax** [comment]
Which Browser?

**Comment by cliffparnitzky** [comment]
Oha, only in Firefox.

Chrome has no probleme: 
![screen](https://cloud.githubusercontent.com/assets/1247552/11515198/eccd3be0-987c-11e5-9c93-6f12f1b0b847.jpg)

**Comment by cliffparnitzky** [comment]
Contao Version is 3.5.0

**Comment by Zeromax** [comment]
@cliffparnitzky Thanks. Edge has the problem to

**Comment by Zeromax** [comment]
can you please check the latest dev branch?
I have fixed it in d74db8d

**Comment by cliffparnitzky** [comment]
Perfect, both problemes (page and ce) are fixed.

Thanks.

**Comment by Zeromax** [comment]
Thanks for testing
