### ISSUE TITLE
Display problemes in page mask

### ISSUE THREAD

**Issue by cliffparnitzky** [Zeromax/contao-sb-admin#29]
There are some display problemes in the page mask:
- height of error message is not enough
- hints of sub pallets are not correct positioned

![screen-03-page_preferences](https://cloud.githubusercontent.com/assets/1247552/11424361/c52c7990-944c-11e5-84df-9ccd0f42ccd9.jpg)

**Comment by Zeromax** [comment]
Thanks for reporting.

**Comment by Zeromax** [comment]
Also the datepicker position is wrong

**Comment by Zeromax** [comment]
Tooltip shouldn't flicker again and Datepicker position is right now.

**Comment by cliffparnitzky** [comment]
Great. Everything okay now. Thanks.
