### ISSUE TITLE
Position Buttons Artikel -> Inhaltselemente

### ISSUE THREAD

**Issue by planepix** [Zeromax/contao-sb-admin#3]
Beim Desktop Icons linksbündig und nicht rechtsbündig. Chrome, Mac.

![inhaltselemente-buttons](https://cloud.githubusercontent.com/assets/1823889/9207834/5c92e14c-4070-11e5-875e-caa8e1e8db44.png)

**Comment by Zeromax** [comment]
implemented in 84568ab
