### ISSUE TITLE
Popover Delay

### ISSUE THREAD

**Issue by Bicet** [Zeromax/contao-sb-admin#33]
Is it possible to set a delay for popover?

**Comment by Zeromax** [comment]
@Bicet what do you mean with delay? And for which popover?

**Comment by Bicet** [comment]
I was talking about the popover on mouse hover the menu on the left or any other link. I've modified the delay on jquery.js and it works as expected now :)

BTW thanks a lot for your hard work!

**Comment by Zeromax** [comment]
Sounds interessting. Can you please share your changes?

**Comment by Bicet** [comment]
On this file: /contao/system/themes/sb-admin/js/jquery.js

`trigger:"hover focus",title:"",delay:0,html:!1,`

I've changed the delay from 0 to { "show": 1500, "hide": 20 }

`trigger:"hover focus",title:"",delay: { "show": 1500, "hide": 20 },html:!1,`

So the tooltip doesn't appear immediately, but after 1,5s and disappear almost immediately.

**Comment by Zeromax** [comment]
improved in 66a1f7f934adcf9a5beb4c9cf12788e1e3dd7a6a
