### ISSUE TITLE
Displayfailure if viewport is zoomed in browser

### ISSUE THREAD

**Issue by agoat** [Zeromax/contao-sb-admin#35]
If the viewport of the browser is zoomed (125%, 150%) then the display order of the input fields are wrong. This happens if there is left a input and right a checkbox. 

The reason is the floating and the height of the checkbox.
Tested in Chrome and Firefox. The easiest way to see thisd is in the backend settings at the "Do not collapse elements" checkbox and the following two URL inputs.

This is easy to fix in the style.css when setting the the margin-bottom for .tl_boxfrom 6 to 8px:
`.tl_box .cbx, -tl_tbox .cbx {margin-top: 52px; margin-bottom: 8px; }`

**Comment by agoat** [comment]
Same problem explained in german #34

**Comment by Zeromax** [comment]
fixed in 62c1148
