### ISSUE TITLE
False selection in file picker in mulitple mode

### ISSUE THREAD

**Issue by agoat** [Zeromax/contao-sb-admin#36]
When selecting images in content element gallery and expanding a folder, the whole folder is then selected. This is annoying when you only want some files within a folder.

It looks like there is an error in the hover.js. Couldn´t find the exact error.

**Comment by agoat** [comment]
Just replaced the hover.js with the one from the flexible theme. Looks like that solved the problem.

**Comment by Zeromax** [comment]
fixed in 0b55752
