### ISSUE TITLE
Dateiverwaltung Upload Button?

### ISSUE THREAD

**Issue by planepix** [Zeromax/contao-sb-admin#4]
Hier wäre es toll, wenn man einen visuellen Button sehen würde. Man tappt im „weissen” :-).

![dateiverwaltung-upload](https://cloud.githubusercontent.com/assets/1823889/9208321/32fdd9a6-4073-11e5-830d-bb87e69579b9.png)

**Comment by Zeromax** [comment]
Ah ;) Das meintest du.

**Comment by Zeromax** [comment]
So besser?
Andere Farbe?

![unbenannt](https://cloud.githubusercontent.com/assets/1867177/9208986/8948914c-4074-11e5-8526-92f838ea64a9.PNG)

**Comment by planepix** [comment]
+1

**Comment by Zeromax** [comment]
Fixed with 11dc084

**Comment by Zeromax** [comment]
Ich muss noch das Hover anpassen...

**Comment by Zeromax** [comment]
fixed with 708cb07
