### ISSUE TITLE
Long input fields in subpalettes not full width

### ISSUE THREAD

**Issue by agoat** [Zeromax/contao-sb-admin#40]
If a text input field with the class long (in DCA 'eval'=> array('tl_class'=>'long')) is inside a subpalette than the field is not rendered with full width. This is because in the style.css the selector is set to the direct div.long childs from .tl_box.

```
.tl_box>div.long,.tl_tbox>div.long {
    width: 97.5%
}

.tl_box>div.long .tl_text,.tl_box>div.long .tl_select,.tl_tbox>div.long .tl_text,.tl_tbox>div.long .tl_select {
    width: 100%
}
```

But when the field is inside a subpalette (e.g. like in my piwik extension) than the .tl_text input field is another level down. It works when removing the direct child selector to somehting like this:

```
.tl_box div.long {
    width: 97.5%
}

.tl_box div.long .tl_text, .tl_box div.long .tl_select {
    width: 100%
}

```

And it´s strange that the selectors exists twice.

**Comment by Zeromax** [comment]
So can you give me a DCA sample or a HTML sample on how to reproduce?
