### ISSUE TITLE
Adding your own custom css to the theme

### ISSUE THREAD

**Issue by renaudkaczmarek** [Zeromax/contao-sb-admin#42]
Hello !

is there a way for you to add the possibility for your users to add custom CSS to correct some issues relative to some extensions ?

In other words, I want to customize the sb-theme without risking to reset the code I have injected in \system\themes\sb-admin\css\style.css when I update it.

I hope you will understand.

Thank you for your time ;)

**Comment by renaudkaczmarek** [comment]
Here is an example. I use Rocksolid Custom Elements and Rocksolid Icons.
So here is the issue I want to correct by myself without disturbing you for every specific extensions I used on Contao : 

![articles test editer l element de contenu id 1506 contao open source cms 3 5](https://cloud.githubusercontent.com/assets/2076897/18488212/c4b30e88-79f8-11e6-819a-d70e1764c4bd.png)

AFTER CORRECTION

```
.rip_icons > a{ font-size: 22px; }
.rip_selected_icon {    font-size: 18px; }
```

![articles test editer l element de contenu id 1506 contao open source cms 3 5s](https://cloud.githubusercontent.com/assets/2076897/18488381/659facf2-79f9-11e6-8261-48a8a85cc37f.png)

**Comment by Zeromax** [comment]
You are already able to do it:

``` php
if (TL_MODE == 'BE')
{
    $GLOBALS['TL_CSS']['your_custom_key'] = $GLOBALS['TL_CONFIG']['debugMode'] ? 
    'path/to/style_src.css'  :  'path/to/style_min.css';
}
```

It's a Contao feature.

**Comment by renaudkaczmarek** [comment]
Thank you so much for your answer, I tried and of course it works. 
But if I want to only override the sb-admin theme ? Unfortunatly, there is no class on the <body> for the sb-admin theme. 

Do you understand ?

**Comment by Zeromax** [comment]
Ah yes I understand.
I think I can add a CSS class in the `be_main.html5` like `sb-admin-theme`.

Also you may use:

``` php
if ( TL_MODE == 'BE' && \Config::get('backendTheme') == 'sb-admin' )
{
    $GLOBALS['TL_CSS']['your_custom_key'] = $GLOBALS['TL_CONFIG']['debugMode'] ? 
    'path/to/style_src.css'  :  'path/to/style_min.css';
}
```

**Comment by renaudkaczmarek** [comment]
Ho that sounds great !

I tried the "Also you may use" but it doesn't seems to work :p 
are sure about "&& \Config::get('backendTheme') == 'sb-admin'" ? It works without it.

**Comment by Zeromax** [comment]
Just use the dev edition CSS class `sb-admin-theme` or try:
`$GLOBALS['TL_CONFIG']['backendTheme'] == 'sb-admin'`

**Comment by renaudkaczmarek** [comment]
Thank you so much for your time ;)
